---
- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: restart grafana
  service:
    name: grafana-server
    state: restarted

- name: restart systemd-resolved
  service:
    name: systemd-resolved.service
    state: restarted