- hosts: docker
  roles:
    - geerlingguy.docker
  tasks:
    - name: create docker volume storage
      file:
        path: /home/docker
        state: directory
        mode: '0775'
        owner: emmet
        group: docker
