---
- name: Update prometheus inventory & alertmanager
  hosts: docker-dev.whemhome
  tasks:
    - name: updating prometheus.yml
      register: promconfig
      copy:
        src: /home/AnsibleMaster/playbooks/WhemlabAnsible/configs/prometheus.yml
        dest: /home/docker/prometheus/prometheus.yml
        owner: root
        group: root        
        mode: 0644

    - name: restart prometheus
      command: docker restart prometheus-prometheus-1
      when: promconfig.changed

    - name: updating alert.yml
      register: alertrules
      copy:
        src: /home/AnsibleMaster/playbooks/WhemlabAnsible/configs/alert.yml
        dest: /home/docker/prometheus/alert.yml
        owner: root
        group: root        
        mode: 0644

    - name: restart alertmanager
      command: docker restart prometheus-alertmanager-1
      when: alertrules.changed

    - name: updating alertmanager.yml
      register: alertmanagerchange
      copy:
        src: /home/AnsibleMaster/playbooks/WhemlabAnsible/configs/alertmanager.yml
        dest: /home/docker/alertmanager/alertmanager.yml
        owner: root
        group: root        
        mode: 0644

    - name: restart alertmanager
      command: docker restart prometheus-alertmanager-1
      when: alertmanager.changed