services:
  core-keeper:
    image: tedtramonte/core-keeper-server
    volumes:
      - /home/docker/core_keeper/server_data:/data
    env_file:
      - /home/docker/core_keeper/core.env
    restart: unless-stopped
    stop_grace_period: 2m