services:
  mc:
    image: itzg/minecraft-server
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: PAPER
    volumes:
      - ./minecraft-data:/data
      - ./plugins:/plugins
    tty: true
    stdin_open: true