services:
  muse:
    image: codetheweb/muse:latest
    restart: always
    volumes:
      - ./muse:/data
    environment:
      - DISCORD_TOKEN=sec
      - YOUTUBE_API_KEY=sec
      - SPOTIFY_CLIENT_ID=sec
      - SPOTIFY_CLIENT_SECRET=sec