services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    container_name: valheim
    cap_add:
      - sys_nice
    volumes:
      - ./valheim-server/config:/config
      - ./valheim-server/data:/opt/valheim
    ports:
      - "5000:5000/udp"
      - "9001:9001/tcp"
    env_file:
      - ./valheim.env
    restart: unless-stopped
    stop_grace_period: 2m