---
- name: install Victoria Metrics as a service
  include: vicmets.yml
  tags: victoria-install

- name: install VMagent as a service and provide basic config
  include: vmagent.yml
  tags: vmagent-install

- name: install Blackbox Exporter as a service and provide basic config
  include: blackbox.yml
  tags: blackbox-install

- name: install alertmanager as a service and provide basic config
  include: alertmanager.yml
  tags: alertmanager-install

- name: install vmalert as a service and provide basic config
  include: vmalert.yml
  tags: vmalert-install

- name: configure grafana
  include: grafana-config.yml
  tags: grafana-config
  