---
- name: Instal Victoria Metrics as a service
  include: vicmets.yml

- name: Instal VMagent as a service and provide basic config
  include: vmagent.yml

- name: Instal Blackbox Exporter as a service and provide basic config
  include: blackbox.yml

- name: Instal vmalert as a service and provide basic config
  include: vmalert.yml