---
#mkdir /etc/vmalert
- name: Create config directory /etc/vmalert
  ansible.builtin.file:
    path: /etc/vmalert
    state: directory
    owner: root
    group: root
    mode: 0644

#create basic config yml
- name: Create basic alerting config
  copy:
    src: vmalert-basic.txt
    dest: /etc/vmalert/alerts/vmalert.yml
    owner: root
    group: root        
    mode: 0644

#create systemd service file in /etc/systemd/system
- name: Create vmalert service in /etc/systemd/system
  copy:
    src: vmalert-service.txt
    dest: /etc/systemd/system/vmalert.service
    owner: root
    group: root        
    mode: 0644

#reload systemd
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

#enable service
- name: Enable and start vmalert service
  service:
    name: vmalert.service
    enabled: yes
    state: started

#firewall rules for port 8880
- firewalld:
    port: 8880/tcp
    permanent: yes
    immediate: yes
    state: enabled
    zone: public