modules:
  tcp_connect:
    prober: tcp

  ssh_banner:
    prober: tcp
    tcp: 
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      query_response:
      - expect: "^SSH-2.0-"

  https_2xx:
    prober: http
    timeout: 8s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      method: GET
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: true
 
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"

  http_post_2xx:
    prober: http
    http:
      method: POST

  icmp:
    prober: icmp
    timeout: 8s
    icmp: 
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      #test