groups:
  - name: ServerAlerts
    rules:
      - alert: InstanceDown
        expr: up{job="servers"} < 1
        for: 5m
      - alert: "HostOutOfDiskSpace"
        expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 15 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
        for: 2m
        labels:
          severity: "warning"
        annotations:
          summary: "Host out of disk space (instance {{ $labels.instance }})"
          description: "Disk is almost full (< 15% left)"
          value: "{{ $value }}"
