global:
  scrape_interval: 30s
  scrape_timeout: 10s

remote_write:
  - url: http://192.168.50.169:8428/api/v1/write

rule_files:
  - alert.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: servers
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090', 'mediadocker.whemhome:9100', 'observium.whemhome:9100', 'docker-dev.whemhome:9100', 'datagraph.whemhome:9100', 'chazprox.whemhome:9100', 'bobbyprox.whemhome:9100', 'pihole.whemhome:9100', 'pfsense.whemhome:9100', 'wg.whemhome:9100', 'ansible.whemhome:9100']

  # the case to use [ssh_banner] module
  - job_name: 'Blackbox_ssh'
    metrics_path: /probe
    params:
      module: [ssh_banner]
    static_configs:
      - targets: ['mediadocker.whemhome', 'observium.whemhome', 'docker-dev.whemhome', 'datagraph.whemhome', 'chazprox.whemhome', 'bobbyprox.whemhome', 'pihole.whemhome', 'pfsense.whemhome', 'wg.whemhome', 'ansible.whemhome']