#pull down current config
- git:
    repo: 'https://github.com/emmetm1/WhemlabAnsible.git'
    dest: /tmp/ansible/vicmets
    clone: yes
    update: yes

#update vmagent configs yml
- name: vmagent configs
  copy:
    src: /tmp/ansible/vicmets/roles/victoria-metrics-home/files/vmagent/
    dest: /etc/vmagent
    remote_src: yes
    backup: yes
    owner: vicstack
    group: vicstack        
    mode: "774"
  notify: reload vmagent config

#update blackbox configs yml
- name: blackbox config
  copy:
    src: /tmp/ansible/vicmets/roles/victoria-metrics-home/files/blackbox.yml
    dest: /etc/blackbox/blackbox.yml
    remote_src: yes
    backup: yes
    owner: vicstack
    group: vicstack        
    mode: "774"
  notify: restart blackbox

#update alertmanager configs yml
- name: alertmanager config
  copy:
    src: /tmp/ansible/vicmets/roles/victoria-metrics-home/files/alertmanager-basic.yml
    dest: /etc/alertmanager/alertmanager.yml
    remote_src: yes
    backup: yes
    owner: vicstack
    group: vicstack        
    mode: "774"
  notify: restart alertmanager

#update vmalert configs yml
- name: vmalert config
  copy:
    src: /tmp/ansible/vicmets/roles/victoria-metrics-home/files/vmalert/
    dest: /etc/vmalert/alerts
    remote_src: yes
    backup: yes
    owner: vicstack
    group: vicstack        
    mode: "774"
  notify: reload vmalert config