- git:
    repo: 'https://github.com/emmetm1/WhemlabAnsible.git'
    dest: /tmp/ansible/vicmets
    clone: yes
    update: yes

#update vmagent configs yml
- name: vmagent configs
  copy:
    src: /tmp/ansible/vicmets/roles/victoria-metrics-home/files/vmagent/
    dest: /etc/vmagent
    remote_src: yes
    backup: yes
    owner: vicstack
    group: vicstack        
    mode: "774"
  notify: reload vmagent config

#update vmagent configs yml
- name: blackbox config
  copy:
    src: /tmp/ansible/vicmets/roles/victoria-metrics-home/files/blackbox.yml
    dest: /etc/blackbox/blackbox.yml
    remote_src: yes
    backup: yes
    owner: vicstack
    group: vicstack        
    mode: "774"
  notify: restart blackbox

- name: Check if blackbox is running
  command: systemctl status blackbox
  ignore_errors: yes

- name: alertmanager config
  copy:
    src: /tmp/ansible/vicmets/roles/victoria-metrics-home/files/alertmanager-basic.yml
    dest: /etc/alertmanager/alertmanager.yml
    remote_src: yes
    backup: yes
    owner: vicstack
    group: vicstack        
    mode: "774"
  notify: restart alertmanager

- name: Check if blackbox is running
  command: systemctl status alertmanager
  ignore_errors: yes

- name: vmalert config
  copy:
    src: /tmp/ansible/vicmets/roles/victoria-metrics-home/files/vmalert/
    dest: /etc/vmalert/alerts
    remote_src: yes
    backup: yes
    owner: vicstack
    group: vicstack        
    mode: "774"
  notify: reload vmalert config

#https://smee.io/0QbeIDKJGdWy02

#https://ansible.whemhome:443/api/v2/job_templates/13/github/